// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gm.proto

using Google.Protobuf;
using Google.Protobuf.Reflection;
using System;

namespace DC.Packet
{
    public sealed partial class SC2S_GM_PARTY_ALL_RANDOM_REQ : IMessage<SC2S_GM_PARTY_ALL_RANDOM_REQ>
    {
        // Implement message serialization and deserialization
        // Other members...
        public MessageDescriptor Descriptor => throw new NotImplementedException();

        public int CalculateSize()
        {
            throw new NotImplementedException();
        }

        public SC2S_GM_PARTY_ALL_RANDOM_REQ Clone()
        {
            throw new NotImplementedException();
        }

        public bool Equals(SC2S_GM_PARTY_ALL_RANDOM_REQ? other)
        {
            throw new NotImplementedException();
        }

        public void MergeFrom(SC2S_GM_PARTY_ALL_RANDOM_REQ message)
        {
            throw new NotImplementedException();
        }

        public void MergeFrom(CodedInputStream input)
        {
            throw new NotImplementedException();
        }

        public void WriteTo(CodedOutputStream output)
        {
            throw new NotImplementedException();
        }
    }

    public sealed partial class SS2C_GM_PARTY_ALL_RANDOM_RES : IMessage<SS2C_GM_PARTY_ALL_RANDOM_RES>
    {
        // Implement message serialization and deserialization
        // Other members...
        public MessageDescriptor Descriptor => throw new NotImplementedException();

        public int CalculateSize()
        {
            throw new NotImplementedException();
        }

        public SS2C_GM_PARTY_ALL_RANDOM_RES Clone()
        {
            throw new NotImplementedException();
        }

        public bool Equals(SS2C_GM_PARTY_ALL_RANDOM_RES? other)
        {
            throw new NotImplementedException();
        }

        public void MergeFrom(SS2C_GM_PARTY_ALL_RANDOM_RES message)
        {
            throw new NotImplementedException();
        }

        public void MergeFrom(CodedInputStream input)
        {
            throw new NotImplementedException();
        }

        public void WriteTo(CodedOutputStream output)
        {
            throw new NotImplementedException();
        }
    }
}
